2018-11-03 18:39:29,946 ERROR: Exception on /api/settingDelete/ [POST] [in g:\termassignment\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "g:\termassignment\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "g:\termassignment\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "g:\termassignment\venv\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "g:\termassignment\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "g:\termassignment\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "g:\termassignment\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "G:\TermAssignment\app\url_mapping.py", line 117, in settingDelete
    if DeleteArea(areaId):
  File "G:\TermAssignment\app\db_io.py", line 129, in DeleteArea
    db.session.delete(de)
  File "g:\termassignment\venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 153, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "g:\termassignment\venv\lib\site-packages\sqlalchemy\orm\session.py", line 1810, in delete
    raise exc.UnmappedInstanceError(instance)
UnmappedInstanceError: Class '__builtin__.NoneType' is not mapped
2018-11-03 18:48:14,247 ERROR: Exception on /api/settingDelete/ [POST] [in g:\termassignment\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "g:\termassignment\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "g:\termassignment\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "g:\termassignment\venv\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "g:\termassignment\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "g:\termassignment\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "g:\termassignment\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "G:\TermAssignment\app\url_mapping.py", line 117, in settingDelete
    if DeleteArea(areaId):
  File "G:\TermAssignment\app\db_io.py", line 129, in DeleteArea
    db.session.delete(de)
  File "g:\termassignment\venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 153, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "g:\termassignment\venv\lib\site-packages\sqlalchemy\orm\session.py", line 1810, in delete
    raise exc.UnmappedInstanceError(instance)
UnmappedInstanceError: Class '__builtin__.NoneType' is not mapped
2018-11-03 18:50:16,924 ERROR: Exception on /api/settingDelete/ [POST] [in g:\termassignment\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "g:\termassignment\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "g:\termassignment\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "g:\termassignment\venv\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "g:\termassignment\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "g:\termassignment\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "g:\termassignment\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "G:\TermAssignment\app\url_mapping.py", line 117, in settingDelete
    if DeleteArea(areaId):
  File "G:\TermAssignment\app\db_io.py", line 129, in DeleteArea
    db.session.delete(de)
  File "g:\termassignment\venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 153, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "g:\termassignment\venv\lib\site-packages\sqlalchemy\orm\session.py", line 1810, in delete
    raise exc.UnmappedInstanceError(instance)
UnmappedInstanceError: Class '__builtin__.NoneType' is not mapped
2018-11-03 18:53:35,601 INFO: server startup [in G:\TermAssignment\app\__init__.py:45]
2018-11-03 18:54:13,151 INFO: server startup [in G:\TermAssignment\app\__init__.py:45]
2018-11-03 19:00:12,151 INFO: server startup [in G:\TermAssignment\app\__init__.py:45]
2018-11-03 19:00:56,954 INFO: server startup [in G:\TermAssignment\app\__init__.py:45]
2018-11-03 19:01:52,311 INFO: server startup [in G:\TermAssignment\app\__init__.py:45]
2018-11-03 19:02:07,296 INFO: server startup [in G:\TermAssignment\app\__init__.py:45]
2018-11-03 19:02:12,796 ERROR: Exception on /api/settingSave/ [POST] [in g:\termassignment\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "g:\termassignment\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "g:\termassignment\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "g:\termassignment\venv\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "g:\termassignment\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "g:\termassignment\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "g:\termassignment\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "G:\TermAssignment\app\url_mapping.py", line 96, in settingSave
    AreaUpdate(areaId, name=areaName, rule_list=rules)
  File "G:\TermAssignment\app\db_io.py", line 100, in AreaUpdate
    for rule in a_rules:
  File "g:\termassignment\venv\lib\site-packages\sqlalchemy\sql\operators.py", line 411, in __getitem__
    return self.operate(getitem, index)
  File "g:\termassignment\venv\lib\site-packages\sqlalchemy\orm\attributes.py", line 180, in operate
    return op(self.comparator, *other, **kwargs)
  File "g:\termassignment\venv\lib\site-packages\sqlalchemy\sql\operators.py", line 411, in __getitem__
    return self.operate(getitem, index)
  File "g:\termassignment\venv\lib\site-packages\sqlalchemy\sql\operators.py", line 214, in operate
    raise NotImplementedError(str(op))
NotImplementedError: <built-in function getitem>
2018-11-03 19:02:42,240 INFO: server startup [in G:\TermAssignment\app\__init__.py:45]
2018-11-03 19:02:47,194 ERROR: Exception on /api/settingSave/ [POST] [in g:\termassignment\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "g:\termassignment\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "g:\termassignment\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "g:\termassignment\venv\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "g:\termassignment\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "g:\termassignment\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "g:\termassignment\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "G:\TermAssignment\app\url_mapping.py", line 96, in settingSave
    AreaUpdate(areaId, name=areaName, rule_list=rules)
  File "G:\TermAssignment\app\db_io.py", line 99, in AreaUpdate
    for rule in Area.rules:
  File "g:\termassignment\venv\lib\site-packages\sqlalchemy\sql\operators.py", line 411, in __getitem__
    return self.operate(getitem, index)
  File "g:\termassignment\venv\lib\site-packages\sqlalchemy\orm\attributes.py", line 180, in operate
    return op(self.comparator, *other, **kwargs)
  File "g:\termassignment\venv\lib\site-packages\sqlalchemy\sql\operators.py", line 411, in __getitem__
    return self.operate(getitem, index)
  File "g:\termassignment\venv\lib\site-packages\sqlalchemy\sql\operators.py", line 214, in operate
    raise NotImplementedError(str(op))
NotImplementedError: <built-in function getitem>
2018-11-03 19:17:12,834 INFO: server startup [in G:\TermAssignment\app\__init__.py:45]
